In [2]:
import pandas as pd
import numpy as np
import duckdb

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', 15)

In [3]:
fin = pd.read_excel('data/School_total_spend_2022-23_Full_Data_Workbook.xlsx', sheet_name=3)
fin.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12031 entries, 0 to 12030
Data columns (total 128 columns):
 #    Column                                                                                            Dtype
---   ------                                                                                            -----
 0    LA                                                                                                int64
 1    LA Name                                                                                           object
 2    Region                                                                                            object
 3    London Borough                                                                                    object
 4    Estab                                                                                             float64
 5    LAEstab                                                                                           int64
 6    URN                                                                                               float64
 7    School Name                                                                                       object
 8    Phase                                                                                             object
 9    Overall Phase                                                                                     object
 10   Lowest age of pupils                                                                              float64
 11   Highest age of pupils                                                                             float64
 12   Type                                                                                              object
 13   Full time equivalent number of pupils in school                                                   float64
 14   Full time equivalent number of pupils in federation                                               float64
 15   % of pupils eligible for FSM                                                                      float64
 16   Period covered by return (months)                                                                 int64
 17   Did Not Supply flag                                                                               object
 18   Federation                                                                                        object
 19   Lead school in federation                                                                         int64
 20   FTE Number of teachers                                                                            float64
 21   Gender                                                                                            object
 22   Urban /Rural                                                                                      object
 23   London Weighting                                                                                  object
 24   % of pupils with EHCP                                                                             float64
 25   % of pupils with SEN support                                                                      float64
 26   % of pupils with English as an additional language                                                float64
 27   % of pupils who are Boarders                                                                      float64
 28   Admissions policy                                                                                 object
 29   PFI                                                                                               object
 30   Has a 6th form                                                                                    object
 31   No of pupils in 6th form                                                                          float64
 32   I01 Funds delegated by the LA                                                                     float64
 33   I02 Funding for 6th form students                                                                 float64
 34   I01/2 Total pre and Post-16 Funding                                                               float64
 35   I03 SEN funding                                                                                   float64
 36   I04 Funding for minority ethnic pupils                                                            float64
 37   I05 Pupil Premium                                                                                 float64
 38   I06 Other government grants                                                                       float64
 39   I07 Other grants and payments                                                                     float64
 40   I08a Income from lettings                                                                         float64
 41   I08b Income from facilities and services                                                          float64
 42   I08a/b Total income from facilities and services                                                  float64
 43   I09 Income from catering                                                                          float64
 44   I10 Receipts from supply teacher insurance claims                                                 float64
 45   I11 Receipts from other insurance claims                                                          float64
 46   I12 Income from contributions to visits etc.                                                      float64
 47   I13 Donations and/or private funds                                                                float64
 48   I15 Pupil focussed extended school funding and / or grants                                        float64
 49   I16 Community focussed school funding and / or grants                                             float64
 50   I17 Community focused school facilities income                                                    float64
 51   I18a Income from the Coronavirus Job Retention Scheme                                             float64
 52   I18b Income from the DfE grant scheme for reimbursing exceptional costs associated with COVID-19  float64
 53   I18c Income from the Â£1bn COVID-19 catch-up package announced on 20 July 2020                     float64
 54   I18d Income from other additional grants                                                          float64
 55   I18 Total additional grant for schools                                                            float64
 56   E01 Teaching Staff                                                                                float64
 57   E02 Supply teaching staff                                                                         float64
 58   E03 Education support staff                                                                       float64
 59   E04 Premises staff                                                                                float64
 60   E05 Administrative and clerical staff                                                             float64
 61   E06 Catering staff                                                                                float64
 62   E07 Cost of other staff                                                                           float64
 63   E08 Indirect employee expenses                                                                    float64
 64   E09 Development and training                                                                      float64
 65   E10 Supply teacher insurance                                                                      float64
 66   E11 Staff related insurance                                                                       float64
 67   E12 Building maintenance and improvement                                                          float64
 68   E13 Grounds maintenance and improvement                                                           float64
 69   E14 Cleaning and caretaking                                                                       float64
 70   E15 Water and sewerage                                                                            float64
 71   E16 Energy                                                                                        float64
 72   E17 Rates                                                                                         float64
 73   E18 Other occupation costs                                                                        float64
 74   E19 Learning resources (not ICT equipment)                                                        float64
 75   E20 ICT learning resources                                                                        float64
 76   E21 Exam fees                                                                                     float64
 77   E22 Administrative supplies                                                                       float64
 78   E23 Other insurance premiums                                                                      float64
 79   E24 Special facilities                                                                            float64
 80   E25 Catering supplies                                                                             float64
 81   E26 Agency supply teaching staff                                                                  float64
 82   E27 Bought in professional services â curriculum                                                  float64
 83   E28a Bought in professional services, other, not PFI                                              float64
 84   E28b Bought in professional services, other, PFI                                                  float64
 85   E28a/b Total bought in professional services                                                      float64
 86   E29 Loan interest                                                                                 float64
 87   E30 Direct revenue financing (revenue contributions to capital)                                   float64
 88   E31 Community focused school staff                                                                float64
 89   E32 Community focused school costs                                                                float64
 90   OB01 Opening pupil-focused revenue balance                                                        float64
 91   OB02 Opening community-focused revenue balance                                                    float64
 92   OB03 Opening capital balance                                                                      float64
 93   CI01 Capital income                                                                               float64
 94   CI03 Voluntary or private income                                                                  float64
 95   CI04 Direct revenue financing                                                                     float64
 96   CE01 Acquisition of land and existing buildings                                                   float64
 97   CE02 New construction, conversion and renovation                                                  float64
 98   CE03 Vehicles, plant, equipment and machinery                                                     float64
 99   CE04 Information and communication technology                                                     float64
 100  B01 Committed revenue balances                                                                    float64
 101  B02 Uncommitted revenue balances                                                                  float64
 102  B03 Devolved formula capital balance                                                              float64
 103  B05 Other capital balances                                                                        float64
 104  B06 Community-focused school revenue balances                                                     float64
 105  B07 Outstanding balance on capital loans to school                                                float64
 106  Revenue Reserve: B01 + B02 + B06                                                                  float64
 107  In-year Balance: Total Income (I01:I18 - E30) - Total Expenditure (E01:E29 + E31 + E32)           float64
 108  Grant Funding: (I01:I07) + I15 + I16 + I18a/b/c/d                                                 float64
 109  Direct Grants: I01:I02 + I06:I07                                                                  float64
 110  Community Grants: I16+I18                                                                         float64
 111  Targeted Grants: I03:I05 + I15                                                                    float64
 112  Self Generated Funding: (I08a/b:I13) + I17                                                        float64
 113  Total Income: I01:I18 - E30                                                                       float64
 114  Teaching Staff  E01                                                                               float64
 115  Supply Staff: E02 + E10 + E26                                                                     float64
 116  Education support staff: E03                                                                      float64
 117  Other Staff Costs: (E07:E09) + E11                                                                float64
 118  Staff Total: (E01:E03) + E05 + (E07: E11) + E26                                                   float64
 119  Maintenance & Improvement: E12 + E13                                                              float64
 120  Premises: (E12:E14) + E04 + E28b                                                                  float64
 121  Catering Expenses: E06 + E25                                                                      float64
 122  Occupation: E06 + (E15:E18) + E23 + E25                                                           float64
 123  Supplies and Services: (E19:E22) + (E27:E28b)                                                     float64
 124  Educational Supplies: (E19:E21)                                                                   float64
 125  Brought in Professional Sevices: (E27 + E28a)                                                     float64
 126  Community Exp: E31 + E32                                                                          float64
 127  Total Expenditure: (E01:E29 + E31 + E32)                                                          float64
dtypes: float64(109), int64(4), object(15)
memory usage: 11.7+ MB

In [1]:
fin['Did N']

NameError: name 'fin' is not defined

In [4]:

fin = pd.read_excel('data/SFB_Academies_2021-22_download.xlsx', sheet_name=1)
fin.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10135 entries, 0 to 10134
Data columns (total 103 columns):
 #    Column                                                           Dtype
---   ------                                                           -----
 0    LAEstab                                                          int64
 1    LA                                                               int64
 2    Estab                                                            int64
 3    URN                                                              int64
 4    Academy UPIN                                                     int64
 5    School Name                                                      object
 6    Period covered by return                                         int64
 7    MAT SAT or Central Services                                      object
 8    Lead UPIN                                                        int64
 9    UID                                                              float64
 10   Company Number                                                   int64
 11   Trust or Company Name                                            object
 12   Date opened                                                      datetime64[ns]
 13   Date closed                                                      datetime64[ns]
 14   Date left or closed if in period                                 datetime64[ns]
 15   Date joined or opened if in period                               datetime64[ns]
 16   Number of pupils in academy (FTE)                                float64
 17   Number of teachers in academy (FTE)                              float64
 18   Gender                                                           object
 19   Overall Phase                                                    object
 20   Phase                                                            object
 21   Type                                                             object
 22   Urban/Rural                                                      object
 23   Region                                                           object
 24   London Borough                                                   object
 25   London Weighting                                                 object
 26   Admissions policy                                                object
 27   PFI                                                              object
 28   % of pupils eligible for FSM                                     float64
 29   % of pupils with an EHCP                                         float64
 30   % of pupils with SEN support                                     float64
 31   % of pupils with English as an additional language               float64
 32   % of pupils who are boarders                                     float64
 33   Has a 6th form                                                   object
 34   No of pupils in 6th form                                         float64
 35   Lowest age of pupils                                             int64
 36   Highest age of pupils                                            int64
 37   Did Not Supply flag                                              object
 38   DFE/EFA Revenue grants (includes Coronavirus Government Funding  object
 39   of which: Coronavirus Government Funding                         object
 40   SEN funding                                                      object
 41   Other DfE/EFA Revenue Grants                                     object
 42   Other income - LA & other Government grants                      object
 43   Government source, non-grant                                     object
 44   Academies                                                        object
 45   Non-Government                                                   object
 46   All income from facilities and services                          object
 47   Income from catering                                             object
 48   Receipts from supply teacher insurance claims                    object
 49   Donations and/or voluntary funds                                 object
 50   Other self-generated income                                      object
 51   Investment income                                                object
 52   Teaching staff                                                   object
 53   Supply teaching staff                                            object
 54   Education support staff                                          object
 55   Administrative and clerical staff                                object
 56   Premises staff                                                   object
 57   Catering staff                                                   object
 58   Other staff                                                      object
 59   Indirect employee expenses                                       object
 60   Staff development and training                                   object
 61   Staff-related insurance                                          object
 62   Supply teacher insurance                                         object
 63   Building and Grounds maintenance and improvement                 object
 64   Cleaning and caretaking                                          object
 65   Water and sewerage                                               object
 66   Energy                                                           object
 67   Rent and Rates                                                   object
 68   Other occupation costs                                           object
 69   Special facilities                                               object
 70   Learning resources (not ICT equipment)                           object
 71   ICT learning resources                                           object
 72   Examination fees                                                 object
 73   Educational Consultancy                                          object
 74   Administrative supplies - non educational                        object
 75   Agency supply teaching staff                                     object
 76   Catering supplies                                                object
 77   Other insurance premiums                                         object
 78   Legal & Professionalservices                                     object
 79   Auditor costs                                                    object
 80   Interest charges for Loan and Bank                               object
 81   Direct revenue financing - Revenue contributions to capital      object
 82   PFI Charges                                                      object
 83   Revenue reserve                                                  object
 84   Share of Revenue Reserve, distributed on per pupil basis
        float64
 85   In year balance                                                  object
 86   Total Grant Funding                                              object
 87   Direct Grants                                                    object
 88   Community Grants                                                 object
 89   Targeted Grants                                                  object
 90   Total Self Generated Funding                                     object
 91   Total Income                                                     object
 92   Supply Staff Costs                                               object
 93   Other Staff Costs                                                object
 94   Total Staff Costs                                                object
 95   Maintenance & Improvement Costs                                  object
 96   Premises Costs                                                   object
 97   Catering Expenses                                                object
 98   Occupation Costs                                                 object
 99   Total Costs of Supplies and Services                             object
 100  Total Costs of Educational Supplies                              object
 101  Costs of Brought in Professional Services                        object
 102  Total Expenditure                                                object
dtypes: datetime64[ns](4), float64(10), int64(10), object(79)
memory usage: 8.0+ MB

In [4]:
import pandas as pd
import numpy as np
import duckdb

pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', 15)

db = duckdb.connect() # No need to pass a file name, we will use a VIEW

In [30]:


df = db.query('SELECT * FROM parquet_scan(\'data/duck/academies_finance.parquet\') WHERE "Overall Phase" = \'Primary\'').to_df()

df

,LAEstab,LA,Estab,URN,Academy UPIN,School Name,Period covered by return,...,Premises Costs,Catering Expenses,Occupation Costs,Total Costs of Supplies and Services,Total Costs of Educational Supplies,Costs of Brought in Professional Services,Total Expenditure
0,8062325,806,2325,145623,140487,Archibald Primary School,12,...,129000.0,155000.0,222000.0,193000.0,148000.0,33000.0,2703000.0
1,3802008,380,2008,138252,121977,Dixons Music Primary,12,...,118000.0,128000.0,179000.0,176000.0,56000.0,29000.0,2122000.0
2,3802018,380,2018,140358,127700,Dixons Marchbank Primary,12,...,117000.0,170000.0,216000.0,206000.0,127000.0,22000.0,2480000.0
3,3802025,380,2025,141375,131394,Dixons Manningham Academy,12,...,122000.0,112000.0,147000.0,179000.0,86000.0,12000.0,2171000.0
4,3032003,303,2003,142586,133453,Eastcote Primary Academy,12,...,34000.0,50000.0,89000.0,107000.0,68000.0,22000.0,1140000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6705,8882096,888,2096,148919,163362,Accrington Huncoat Primary School,6,...,28000.0,14000.0,36000.0,40000.0,27000.0,0.0,557000.0
6706,8882108,888,2108,148920,163365,Oswaldtwistle West End Primary School,6,...,5000.0,37000.0,57000.0,52000.0,35000.0,9000.0,556000.0
6707,8453019,845,3019,148917,163676,Ditchling St Margaret's Church of England Prim...,4,...,18000.0,6000.0,21000.0,16000.0,12000.0,2000.0,300000.0
6708,9383060,938,3060,148924,163675,Albourne Church of England Primary School,5,...,21000.0,15000.0,31000.0,71000.0,46000.0,11000.0,445000.0
6709,9383352,938,3352,149129,163840,St Wilfrid's CofE Primary School,2,...,24000.0,13000.0,23000.0,32000.0,13000.0,15000.0,347000.0

In [31]:
#df['Did Not Supply flag'] = str(df['Did Not Supply flag'], encoding='latin-1')
df['Did Not Supply flag'].unique()

array([None, 'DNS'], dtype=object)